version: '3.7'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Prometheus 웹 UI 포트
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # 설정 파일 매핑
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # Grafana 웹 UI 포트
    environment:
      - GF_SECURITY_ADMIN_USER=admin # Grafana 기본 사용자 이름
      - GF_SECURITY_ADMIN_PASSWORD=admin # Grafana 기본 비밀번호
  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    ports:
      - "3100:3100" # Loki의 기본 API 포트
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - /var/log:/var/log # 호스트의 로그 디렉토리
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml