# AWS LoadBalancer Controller 설치
---

- name: Load variables from vars file
  include_vars: ../../vars/aws_vars.yml

- name: Download iam_policy.json for AWS Load Balancer Controller
  get_url:
    url: https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json
    dest: /home/ec2-user/aws/iam_policy.json
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Create IAM policy for AWS Load Balancer Controller
  command: >
    aws iam create-policy
    --policy-name AWSLoadBalancerControllerIAMPolicy
    --policy-document file:///home/ec2-user/aws/iam_policy.json
    --profile {{ aws_profile }}
  register: create_policy_output
  ignore_errors: yes

- name: Create IAM OIDC provider for EKS cluster
  command: >
    eksctl utils associate-iam-oidc-provider
    --region {{ aws_region }}
    --cluster {{ cluster_name }}
    --approve
    --profile {{ aws_profile }}
  register: associate_oidc_output
  ignore_errors: yes

- name: Create IAM service account for Load Balancer Controller
  command: >
    eksctl create iamserviceaccount
    --cluster {{ cluster_name }}
    --namespace kube-system
    --name aws-load-balancer-controller
    --attach-policy-arn arn:aws:iam::{{ aws_account_id }}:policy/AWSLoadBalancerControllerIAMPolicy
    --approve
    --profile {{ aws_profile }}
  register: iam_service_account_output
  ignore_errors: yes

- name: Add Helm repository for AWS Load Balancer Controller
  command: "helm repo add eks https://aws.github.io/eks-charts"
  register: helm_repo_add_eks
  failed_when: helm_repo_add_eks.rc not in [0, 1]
  changed_when: helm_repo_add_eks.rc == 0

- name: Update Helm repositories
  command: "helm repo update"

- name: Find VPC ID for EKS cluster
  command: >
    aws eks describe-cluster
    --name {{ cluster_name }}
    --region {{ aws_region }}
    --profile {{ aws_profile }}
    --query "cluster.resourcesVpcConfig.vpcId"
    --output text
  register: vpc_id_output

- name: Install AWS Load Balancer Controller with Helm
  command: >
    helm install aws-load-balancer-controller eks/aws-load-balancer-controller
    -n kube-system
    --set clusterName={{ cluster_name }}
    --set serviceAccount.create=false
    --set serviceAccount.name=aws-load-balancer-controller
    --set region={{ aws_region }}
    --set vpcId={{ vpc_id_output.stdout }}
    --set image.repository=602401143452.dkr.ecr.{{ aws_region }}.amazonaws.com/amazon/aws-load-balancer-controller
